<?php
return array (
  'HANDLE_WORK_MIN_TIME2' => '36',
  'HANDLE_WORK_MIN_USER2' => '2',
  'HANDLE_WORK_MAX_USER2' => '7',
  'HANDLE_HOLI_MIN_TIME2' => '24',
  'HANDLE_HOLI_MIN_USER2' => '2',
  'HANDLE_HOLI_MAX_USER2' => '7',
  'HANDLE_WORK_MIN_TIME3' => '36',
  'HANDLE_WORK_MIN_USER3' => '4',
  'HANDLE_WORK_MAX_USER3' => '7',
  'HANDLE_HOLI_MIN_TIME3' => '24',
  'HANDLE_HOLI_MIN_USER3' => '4',
  'HANDLE_HOLI_MAX_USER3' => '7',
);